#############################################################################
# Makefile for building: app
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  qt.pro
# Template: app
# Command: /opt/qt59/bin/qmake -o Makefile qt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/opt/qt59/include -I/opt/qt59/include/QtWidgets -I/opt/qt59/include/QtGui -I/opt/qt59/include/QtCore -I. -isystem /usr/include/libdrm -I/opt/qt59/mkspecs/linux-g++
QMAKE         = /opt/qt59/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt59/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt59/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = app1.0.0
DISTDIR = /home/fyl/qt/.tmp/app1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt59/lib
LIBS          = $(SUBLIBS) -L/opt/qt59/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qt.cpp 
OBJECTS       = qt.o
DIST          = /opt/qt59/mkspecs/features/spec_pre.prf \
		/opt/qt59/mkspecs/common/unix.conf \
		/opt/qt59/mkspecs/common/linux.conf \
		/opt/qt59/mkspecs/common/sanitize.conf \
		/opt/qt59/mkspecs/common/gcc-base.conf \
		/opt/qt59/mkspecs/common/gcc-base-unix.conf \
		/opt/qt59/mkspecs/common/g++-base.conf \
		/opt/qt59/mkspecs/common/g++-unix.conf \
		/opt/qt59/mkspecs/qconfig.pri \
		/opt/qt59/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt59/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt59/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_core.pri \
		/opt/qt59/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt59/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt59/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt59/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_help.pri \
		/opt/qt59/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_network.pri \
		/opt/qt59/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt59/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt59/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt59/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt59/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt59/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt59/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt59/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt59/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt59/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt59/mkspecs/features/qt_functions.prf \
		/opt/qt59/mkspecs/features/qt_config.prf \
		/opt/qt59/mkspecs/linux-g++/qmake.conf \
		/opt/qt59/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt59/mkspecs/features/exclusive_builds.prf \
		/opt/qt59/mkspecs/features/toolchain.prf \
		/opt/qt59/mkspecs/features/default_pre.prf \
		/opt/qt59/mkspecs/features/resolve_config.prf \
		/opt/qt59/mkspecs/features/default_post.prf \
		/opt/qt59/mkspecs/features/warn_on.prf \
		/opt/qt59/mkspecs/features/qt.prf \
		/opt/qt59/mkspecs/features/resources.prf \
		/opt/qt59/mkspecs/features/moc.prf \
		/opt/qt59/mkspecs/features/unix/opengl.prf \
		/opt/qt59/mkspecs/features/uic.prf \
		/opt/qt59/mkspecs/features/unix/thread.prf \
		/opt/qt59/mkspecs/features/qmake_use.prf \
		/opt/qt59/mkspecs/features/file_copies.prf \
		/opt/qt59/mkspecs/features/testcase_targets.prf \
		/opt/qt59/mkspecs/features/exceptions.prf \
		/opt/qt59/mkspecs/features/yacc.prf \
		/opt/qt59/mkspecs/features/lex.prf \
		qt.pro  qt.cpp
QMAKE_TARGET  = app
DESTDIR       = 
TARGET        = app


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt.pro /opt/qt59/mkspecs/linux-g++/qmake.conf /opt/qt59/mkspecs/features/spec_pre.prf \
		/opt/qt59/mkspecs/common/unix.conf \
		/opt/qt59/mkspecs/common/linux.conf \
		/opt/qt59/mkspecs/common/sanitize.conf \
		/opt/qt59/mkspecs/common/gcc-base.conf \
		/opt/qt59/mkspecs/common/gcc-base-unix.conf \
		/opt/qt59/mkspecs/common/g++-base.conf \
		/opt/qt59/mkspecs/common/g++-unix.conf \
		/opt/qt59/mkspecs/qconfig.pri \
		/opt/qt59/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt59/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt59/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_core.pri \
		/opt/qt59/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt59/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt59/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt59/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_help.pri \
		/opt/qt59/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_network.pri \
		/opt/qt59/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt59/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt59/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt59/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt59/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt59/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt59/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt59/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt59/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt59/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt59/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt59/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt59/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt59/mkspecs/features/qt_functions.prf \
		/opt/qt59/mkspecs/features/qt_config.prf \
		/opt/qt59/mkspecs/linux-g++/qmake.conf \
		/opt/qt59/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt59/mkspecs/features/exclusive_builds.prf \
		/opt/qt59/mkspecs/features/toolchain.prf \
		/opt/qt59/mkspecs/features/default_pre.prf \
		/opt/qt59/mkspecs/features/resolve_config.prf \
		/opt/qt59/mkspecs/features/default_post.prf \
		/opt/qt59/mkspecs/features/warn_on.prf \
		/opt/qt59/mkspecs/features/qt.prf \
		/opt/qt59/mkspecs/features/resources.prf \
		/opt/qt59/mkspecs/features/moc.prf \
		/opt/qt59/mkspecs/features/unix/opengl.prf \
		/opt/qt59/mkspecs/features/uic.prf \
		/opt/qt59/mkspecs/features/unix/thread.prf \
		/opt/qt59/mkspecs/features/qmake_use.prf \
		/opt/qt59/mkspecs/features/file_copies.prf \
		/opt/qt59/mkspecs/features/testcase_targets.prf \
		/opt/qt59/mkspecs/features/exceptions.prf \
		/opt/qt59/mkspecs/features/yacc.prf \
		/opt/qt59/mkspecs/features/lex.prf \
		qt.pro \
		/opt/qt59/lib/libQt5Widgets.prl \
		/opt/qt59/lib/libQt5Gui.prl \
		/opt/qt59/lib/libQt5Core.prl
	$(QMAKE) -o Makefile qt.pro
/opt/qt59/mkspecs/features/spec_pre.prf:
/opt/qt59/mkspecs/common/unix.conf:
/opt/qt59/mkspecs/common/linux.conf:
/opt/qt59/mkspecs/common/sanitize.conf:
/opt/qt59/mkspecs/common/gcc-base.conf:
/opt/qt59/mkspecs/common/gcc-base-unix.conf:
/opt/qt59/mkspecs/common/g++-base.conf:
/opt/qt59/mkspecs/common/g++-unix.conf:
/opt/qt59/mkspecs/qconfig.pri:
/opt/qt59/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_charts.pri:
/opt/qt59/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt59/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_core.pri:
/opt/qt59/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt59/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_designer.pri:
/opt/qt59/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_gui.pri:
/opt/qt59/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_help.pri:
/opt/qt59/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_network.pri:
/opt/qt59/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt59/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt59/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt59/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_qml.pri:
/opt/qt59/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt59/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_quick.pri:
/opt/qt59/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt59/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_sql.pri:
/opt/qt59/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_svg.pri:
/opt/qt59/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt59/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt59/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt59/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt59/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_xml.pri:
/opt/qt59/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt59/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt59/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt59/mkspecs/features/qt_functions.prf:
/opt/qt59/mkspecs/features/qt_config.prf:
/opt/qt59/mkspecs/linux-g++/qmake.conf:
/opt/qt59/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt59/mkspecs/features/exclusive_builds.prf:
/opt/qt59/mkspecs/features/toolchain.prf:
/opt/qt59/mkspecs/features/default_pre.prf:
/opt/qt59/mkspecs/features/resolve_config.prf:
/opt/qt59/mkspecs/features/default_post.prf:
/opt/qt59/mkspecs/features/warn_on.prf:
/opt/qt59/mkspecs/features/qt.prf:
/opt/qt59/mkspecs/features/resources.prf:
/opt/qt59/mkspecs/features/moc.prf:
/opt/qt59/mkspecs/features/unix/opengl.prf:
/opt/qt59/mkspecs/features/uic.prf:
/opt/qt59/mkspecs/features/unix/thread.prf:
/opt/qt59/mkspecs/features/qmake_use.prf:
/opt/qt59/mkspecs/features/file_copies.prf:
/opt/qt59/mkspecs/features/testcase_targets.prf:
/opt/qt59/mkspecs/features/exceptions.prf:
/opt/qt59/mkspecs/features/yacc.prf:
/opt/qt59/mkspecs/features/lex.prf:
qt.pro:
/opt/qt59/lib/libQt5Widgets.prl:
/opt/qt59/lib/libQt5Gui.prl:
/opt/qt59/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt59/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qt.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt59/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/qt59/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

qt.o: qt.cpp /opt/qt59/include/QtWidgets/QApplication \
		/opt/qt59/include/QtWidgets/qapplication.h \
		/opt/qt59/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt59/include/QtGui/qtguiglobal.h \
		/opt/qt59/include/QtCore/qglobal.h \
		/opt/qt59/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt59/include/QtCore/qconfig.h \
		/opt/qt59/include/QtCore/qtcore-config.h \
		/opt/qt59/include/QtCore/qsystemdetection.h \
		/opt/qt59/include/QtCore/qprocessordetection.h \
		/opt/qt59/include/QtCore/qcompilerdetection.h \
		/opt/qt59/include/QtCore/qtypeinfo.h \
		/opt/qt59/include/QtCore/qsysinfo.h \
		/opt/qt59/include/QtCore/qlogging.h \
		/opt/qt59/include/QtCore/qflags.h \
		/opt/qt59/include/QtCore/qatomic.h \
		/opt/qt59/include/QtCore/qbasicatomic.h \
		/opt/qt59/include/QtCore/qatomic_bootstrap.h \
		/opt/qt59/include/QtCore/qgenericatomic.h \
		/opt/qt59/include/QtCore/qatomic_cxx11.h \
		/opt/qt59/include/QtCore/qatomic_msvc.h \
		/opt/qt59/include/QtCore/qglobalstatic.h \
		/opt/qt59/include/QtCore/qmutex.h \
		/opt/qt59/include/QtCore/qnumeric.h \
		/opt/qt59/include/QtCore/qversiontagging.h \
		/opt/qt59/include/QtGui/qtgui-config.h \
		/opt/qt59/include/QtWidgets/qtwidgets-config.h \
		/opt/qt59/include/QtCore/qcoreapplication.h \
		/opt/qt59/include/QtCore/qstring.h \
		/opt/qt59/include/QtCore/qchar.h \
		/opt/qt59/include/QtCore/qbytearray.h \
		/opt/qt59/include/QtCore/qrefcount.h \
		/opt/qt59/include/QtCore/qnamespace.h \
		/opt/qt59/include/QtCore/qarraydata.h \
		/opt/qt59/include/QtCore/qstringbuilder.h \
		/opt/qt59/include/QtCore/qobject.h \
		/opt/qt59/include/QtCore/qobjectdefs.h \
		/opt/qt59/include/QtCore/qobjectdefs_impl.h \
		/opt/qt59/include/QtCore/qlist.h \
		/opt/qt59/include/QtCore/qalgorithms.h \
		/opt/qt59/include/QtCore/qiterator.h \
		/opt/qt59/include/QtCore/qhashfunctions.h \
		/opt/qt59/include/QtCore/qpair.h \
		/opt/qt59/include/QtCore/qbytearraylist.h \
		/opt/qt59/include/QtCore/qstringlist.h \
		/opt/qt59/include/QtCore/qregexp.h \
		/opt/qt59/include/QtCore/qstringmatcher.h \
		/opt/qt59/include/QtCore/qcoreevent.h \
		/opt/qt59/include/QtCore/qscopedpointer.h \
		/opt/qt59/include/QtCore/qmetatype.h \
		/opt/qt59/include/QtCore/qvarlengtharray.h \
		/opt/qt59/include/QtCore/qcontainerfwd.h \
		/opt/qt59/include/QtCore/qobject_impl.h \
		/opt/qt59/include/QtCore/qeventloop.h \
		/opt/qt59/include/QtGui/qwindowdefs.h \
		/opt/qt59/include/QtGui/qwindowdefs_win.h \
		/opt/qt59/include/QtCore/qpoint.h \
		/opt/qt59/include/QtCore/qsize.h \
		/opt/qt59/include/QtGui/qcursor.h \
		/opt/qt59/include/QtWidgets/qdesktopwidget.h \
		/opt/qt59/include/QtWidgets/qwidget.h \
		/opt/qt59/include/QtCore/qmargins.h \
		/opt/qt59/include/QtGui/qpaintdevice.h \
		/opt/qt59/include/QtCore/qrect.h \
		/opt/qt59/include/QtGui/qpalette.h \
		/opt/qt59/include/QtGui/qcolor.h \
		/opt/qt59/include/QtGui/qrgb.h \
		/opt/qt59/include/QtGui/qrgba64.h \
		/opt/qt59/include/QtGui/qbrush.h \
		/opt/qt59/include/QtCore/qvector.h \
		/opt/qt59/include/QtGui/qmatrix.h \
		/opt/qt59/include/QtGui/qpolygon.h \
		/opt/qt59/include/QtGui/qregion.h \
		/opt/qt59/include/QtCore/qdatastream.h \
		/opt/qt59/include/QtCore/qiodevice.h \
		/opt/qt59/include/QtCore/qline.h \
		/opt/qt59/include/QtGui/qtransform.h \
		/opt/qt59/include/QtGui/qpainterpath.h \
		/opt/qt59/include/QtGui/qimage.h \
		/opt/qt59/include/QtGui/qpixelformat.h \
		/opt/qt59/include/QtGui/qpixmap.h \
		/opt/qt59/include/QtCore/qsharedpointer.h \
		/opt/qt59/include/QtCore/qshareddata.h \
		/opt/qt59/include/QtCore/qhash.h \
		/opt/qt59/include/QtCore/qsharedpointer_impl.h \
		/opt/qt59/include/QtGui/qfont.h \
		/opt/qt59/include/QtGui/qfontmetrics.h \
		/opt/qt59/include/QtGui/qfontinfo.h \
		/opt/qt59/include/QtWidgets/qsizepolicy.h \
		/opt/qt59/include/QtGui/qkeysequence.h \
		/opt/qt59/include/QtGui/qevent.h \
		/opt/qt59/include/QtCore/qvariant.h \
		/opt/qt59/include/QtCore/qmap.h \
		/opt/qt59/include/QtCore/qdebug.h \
		/opt/qt59/include/QtCore/qtextstream.h \
		/opt/qt59/include/QtCore/qlocale.h \
		/opt/qt59/include/QtCore/qset.h \
		/opt/qt59/include/QtCore/qcontiguouscache.h \
		/opt/qt59/include/QtCore/qurl.h \
		/opt/qt59/include/QtCore/qurlquery.h \
		/opt/qt59/include/QtCore/qfile.h \
		/opt/qt59/include/QtCore/qfiledevice.h \
		/opt/qt59/include/QtGui/qvector2d.h \
		/opt/qt59/include/QtGui/qtouchdevice.h \
		/opt/qt59/include/QtGui/qguiapplication.h \
		/opt/qt59/include/QtGui/qinputmethod.h \
		/opt/qt59/include/QtWidgets/QPushButton \
		/opt/qt59/include/QtWidgets/qpushbutton.h \
		/opt/qt59/include/QtWidgets/qabstractbutton.h \
		/opt/qt59/include/QtGui/qicon.h \
		/opt/qt59/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt.o qt.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

